from viewhandler import ViewHandler
from index import IndexPage
from comment import CommentHandler
from likes import LikesHandler
from login import LoginPage
from logout import LogoutPage
from newpost import NewPostPage
from post import PostPage
from signup import SignupPage
from welcome import WelcomePage
